import { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation strings
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.users': 'Users',
    'nav.doctors': 'Doctors',
    'nav.patients': 'Patients',
    'nav.bookings': 'Bookings',
    'nav.paymentPlans': 'Payment Plans',
    'nav.patientPlanSubscriptions': 'Plan Subscriptions',
    'nav.withdrawals': 'Withdrawals',
    'nav.coupons': 'Coupons',
    'nav.reviews': 'Reviews',
    
    // Common
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.actions': 'Actions',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.back': 'Back',
    'common.logout': 'Logout',
    'common.showing': 'Showing',
    'common.to': 'to',
    'common.of': 'of',
    'common.results': 'results',
    'common.previous': 'Previous',
    'common.next': 'Next',
    
    // Dashboard
    'dashboard.title': 'Dashboard Overview',
    'dashboard.welcome': 'Welcome to Estraht Admin Panel',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.totalDoctors': 'Total Doctors',
    'dashboard.totalPatients': 'Total Patients',
    'dashboard.transactions': 'Transactions',
    'dashboard.activeCoupons': 'Active Coupons',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.manageUsers': 'Manage Users',
    'dashboard.manageDoctors': 'Manage Doctors',
    'dashboard.managePatients': 'Manage Patients',
    'dashboard.viewTransactions': 'View Transactions',
    'dashboard.manageCoupons': 'Manage Coupons',
    
    // Login
    'login.title': 'Estraht Admin',
    'login.subtitle': 'Sign in to access the dashboard',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    
    // Doctors
    'doctors.title': 'Doctors Management',
    'doctors.subtitle': 'Manage doctors, their profiles, and specializations',
    'doctors.addDoctor': 'Add Doctor',
    'doctors.totalDoctors': 'Total Doctors',
    'doctors.avgRating': 'Avg Rating',
    'doctors.totalSessions': 'Total Sessions',
    'doctors.totalPatients': 'Total Patients',
    'doctors.search': 'Search by name, email, or specialization...',
    'doctors.doctor': 'Doctor',
    'doctors.contact': 'Contact',
    'doctors.specialization': 'Specialization',
    'doctors.experience': 'Experience',
    'doctors.rating': 'Rating',
    'doctors.price': 'Price',
    'doctors.patients': 'Patients',
    'doctors.noDoctors': 'No doctors found',
    'doctors.createTitle': 'Add New Doctor',
    'doctors.fullName': 'Full Name',
    'doctors.email': 'Email',
    'doctors.phone': 'Phone Number',
    'doctors.age': 'Age',
    'doctors.gender': 'Gender',
    'doctors.yearsOfExp': 'Years of Experience',
    'doctors.bookingPrice': 'Booking Price',
    'doctors.profileImage': 'Profile Image URL',
    'doctors.bio': 'Bio',
    'doctors.selectGender': 'Select gender',
    'doctors.male': 'Male',
    'doctors.female': 'Female',
    'doctors.other': 'Other',
    'doctors.loading': 'Loading doctors...',
    'doctors.empty': 'No doctors found',
    'doctors.deleteConfirm': 'Are you sure you want to delete this doctor?',
    'doctors.viewProfile': 'View Profile',
    'doctors.notAvailable': 'N/A',
    'doctors.yearsSuffix': 'years',
    
    // Patients
    'patients.title': 'Patients Management',
    'patients.subtitle': 'Manage patient records and information',
    'patients.addPatient': 'Add Patient',
    'patients.totalPatients': 'Total Patients',
    'patients.malePatients': 'Male Patients',
    'patients.femalePatients': 'Female Patients',
    'patients.search': 'Search by name, email, or phone...',
    'patients.patient': 'Patient',
    'patients.email': 'Email',
    'patients.phone': 'Phone',
    'patients.age': 'Age',
    'patients.gender': 'Gender',
    'patients.registered': 'Registered',
    'patients.noPatients': 'No patients found',
    'patients.createTitle': 'Add New Patient',
    'patients.fullName': 'Full Name',
    'patients.selectGender': 'Select gender',
    'patients.male': 'Male',
    'patients.female': 'Female',
    'patients.other': 'Other',
    'patients.profileImage': 'Profile Image URL',
    'patients.createError': 'Failed to create patient',
    'patients.createSuccess': 'Patient created successfully',
    
    // Bookings
    'bookings.title': 'Bookings',
    'bookings.subtitle': 'Manage all medical appointments',
    'bookings.bookAppointment': 'Book an Appointment',
    'bookings.total': 'Total',
    'bookings.pending': 'Pending',
    'bookings.confirmed': 'Confirmed',
    'bookings.completed': 'Completed',
    'bookings.cancelled': 'Cancelled',
    'bookings.search': 'Search by doctor, patient, or time slot...',
    'bookings.allStatus': 'All Status',
    'bookings.patient': 'Patient',
    'bookings.doctor': 'Doctor',
    'bookings.date': 'Date',
    'bookings.timeSlot': 'Time Slot',
    'bookings.status': 'Status',
    'bookings.noAppointments': 'No appointments found',
    'bookings.createTitle': 'Create New Appointment',
    'bookings.selectDoctor': 'Select a doctor',
    'bookings.selectPatient': 'Select a patient',
    'bookings.appointmentDate': 'Appointment Date',
    'bookings.createAppointment': 'Create Appointment',
    'bookings.loading': 'Loading appointments...',
    'bookings.deleteConfirm': 'Are you sure you want to delete this appointment?',
    'bookings.createError': 'Failed to create appointment',
    'bookings.unknownPatient': 'Unknown Patient',
    'bookings.unknownDoctor': 'Unknown Doctor',
    
    // Reviews
    'reviews.title': 'Reviews Management',
    'reviews.subtitle': 'Manage patient reviews and ratings',
    'reviews.totalReviews': 'Total Reviews',
    'reviews.averageRating': 'Average Rating',
    'reviews.search': 'Search by comment, rating, booking ID, patient ID, or doctor ID...',
    'reviews.reviewId': 'Review ID',
    'reviews.bookingId': 'Booking ID',
    'reviews.patientId': 'Patient ID',
    'reviews.doctorId': 'Doctor ID',
    'reviews.patientEmail': 'Patient Email',
    'reviews.doctorEmail': 'Doctor Email',
    'reviews.rating': 'Rating',
    'reviews.comment': 'Comment',
    'reviews.createdAt': 'Created At',
    'reviews.noReviews': 'No reviews found',
    'reviews.noComment': 'No comment',
    'reviews.deleteConfirm': 'Are you sure you want to delete this review?',
    
    // Users
    'users.title': 'Users Management',
    'users.subtitle': 'Manage admin users and permissions',
    'users.addUser': 'Add User',
    'users.totalUsers': 'Total Users',
    'users.activeUsers': 'Active Users',
    'users.inactiveUsers': 'Inactive Users',
    'users.searchPlaceholder': 'Search by email or name...',
    'users.table.user': 'User',
    'users.table.email': 'Email',
    'users.table.role': 'Role',
    'users.table.status': 'Status',
    'users.table.lastLogin': 'Last Login',
    'users.table.actions': 'Actions',
    'users.loading': 'Loading users...',
    'users.empty': 'No users found',
    'users.deleteConfirm': 'Are you sure you want to delete this user?',
    'users.status.active': 'Active',
    'users.status.inactive': 'Inactive',
    'users.never': 'Never',
    'users.notAvailable': 'N/A',
    'users.createTitle': 'Create New Admin User',
    'users.createError': 'Failed to create user',
    'users.createSuccess': 'User created successfully',
    'users.form.fullName': 'Full Name',
    'users.form.fullNamePlaceholder': 'Admin Name',
    'users.form.passwordPlaceholder': 'Enter a secure password',
    'users.form.roleAdmin': 'Admin',
    'users.form.roleHelp': 'Role is set to admin by default.',
    'users.form.creating': 'Creating...',
    'users.form.create': 'Create User',
    
    // Transactions
    'transactions.title': 'Transactions',
    'transactions.subtitle': 'Monitor all financial transactions and payments',
    'transactions.totalAmount': 'Total Amount',
    'transactions.successful': 'Successful',
    'transactions.pending': 'Pending',
    'transactions.failed': 'Failed',
    'transactions.searchPlaceholder': 'Search by doctor ID, patient ID, or booking ID...',
    'transactions.filter.all': 'All Status',
    'transactions.filter.success': 'Success',
    'transactions.filter.waiting': 'Pending',
    'transactions.filter.failed': 'Failed',
    'transactions.filter.currency': 'Filter by Currency',
    'transactions.filter.currencyAll': 'All Currencies',
    'transactions.filter.currencyUSD': 'USD',
    'transactions.filter.currencyMRU': 'MRU',
    'transactions.table.id': 'Transaction ID',
    'transactions.table.type': 'Type',
    'transactions.table.doctorId': 'Doctor ID',
    'transactions.table.patientId': 'Patient ID',
    'transactions.table.amount': 'Amount',
    'transactions.table.status': 'Status',
    'transactions.table.date': 'Date',
    'transactions.table.paymentGateway': 'Payment Gateway',
    'transactions.table.paymentCurrency': 'Currency',
    'transactions.table.operationId': 'Operation ID',
    'transactions.empty': 'No transactions found',
    'transactions.viewDetails': 'View Details',
    'transactions.detailTitle': 'Transaction Details',
    'transactions.detail.doctor': 'Doctor',
    'transactions.detail.patient': 'Patient',
    'transactions.detail.transactionInfo': 'Transaction Information',
    'transactions.detail.name': 'Name',
    'transactions.detail.email': 'Email',
    'transactions.detail.id': 'ID',
    
    // Payment Plans
    'paymentPlans.title': 'Payment Plans',
    'paymentPlans.subtitle': 'Manage doctor payment plans',
    'paymentPlans.addPlan': 'Add Plan',
    'paymentPlans.total': 'Total Plans',
    'paymentPlans.active': 'Active',
    'paymentPlans.search': 'Search by plan name or doctor...',
    'paymentPlans.table.name': 'Plan Name',
    'paymentPlans.table.doctor': 'Doctor',
    'paymentPlans.table.price': 'Price',
    'paymentPlans.table.duration': 'Duration',
    'paymentPlans.table.status': 'Status',
    'paymentPlans.empty': 'No payment plans found',
    'paymentPlans.deleteConfirm': 'Are you sure you want to delete this plan?',
    
    // Patient Plan Subscriptions
    'subscriptions.title': 'Plan Subscriptions',
    'subscriptions.subtitle': 'View and manage patient plan subscriptions',
    'subscriptions.total': 'Total',
    'subscriptions.active': 'Active',
    'subscriptions.expired': 'Expired',
    'subscriptions.search': 'Search by patient or plan...',
    'subscriptions.table.patient': 'Patient',
    'subscriptions.table.plan': 'Plan',
    'subscriptions.table.status': 'Status',
    'subscriptions.table.startDate': 'Start',
    'subscriptions.table.endDate': 'End',
    'subscriptions.empty': 'No subscriptions found',
    'subscriptions.deleteConfirm': 'Are you sure you want to delete this subscription?',
    
    // Coupons
    'coupons.title': 'Coupons Management',
    'coupons.subtitle': 'Create and manage discount coupons',
    'coupons.addCoupon': 'Add Coupon',
    'coupons.total': 'Total Coupons',
    'coupons.active': 'Active',
    'coupons.used': 'Used',
    'coupons.expired': 'Expired',
    'coupons.search': 'Search by coupon code or user...',
    'coupons.table.code': 'Coupon Code',
    'coupons.table.value': 'Value',
    'coupons.table.forUser': 'For User',
    'coupons.table.validUntil': 'Valid Until',
    'coupons.table.usage': 'Usage',
    'coupons.table.status': 'Status',
    'coupons.empty': 'No coupons found',
    'coupons.allUsers': 'All Users',
    'coupons.usage.oneTime': 'One-time',
    'coupons.usage.uses': 'uses',
    'coupons.status.active': 'Active',
    'coupons.status.used': 'Used',
    'coupons.status.expired': 'Expired',
    'coupons.deleteConfirm': 'Are you sure you want to delete this coupon?',
    'coupons.createTitle': 'Create New Coupon',
    'coupons.form.code': 'Coupon Code',
    'coupons.form.value': 'Discount Value',
    'coupons.form.valuePlaceholder': '10% or $10',
    'coupons.form.validUntil': 'Valid Until',
    'coupons.form.forUser': 'For User (Optional)',
    'coupons.form.forUserPlaceholder': 'User ID or email',
    'coupons.form.forUserHelp': 'Leave empty for all users',
    'coupons.form.oneTimeUse': 'One-time use only',
    'coupons.form.numberOfUses': 'Number of Uses',
    'coupons.form.creating': 'Creating...',
    'coupons.form.create': 'Create Coupon',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.users': 'المستخدمون',
    'nav.doctors': 'الأطباء',
    'nav.patients': 'المرضى',
    'nav.bookings': 'الحجوزات',
    'nav.paymentPlans': 'خطط الدفع',
    'nav.patientPlanSubscriptions': 'اشتراكات الخطط',
    'nav.withdrawals': 'السحوبات',
    'nav.coupons': 'الكوبونات',
    'nav.reviews': 'التقييمات',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.search': 'بحث',
    'common.actions': 'الإجراءات',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    'common.close': 'إغلاق',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.create': 'إنشاء',
    'common.update': 'تحديث',
    'common.back': 'رجوع',
    'common.logout': 'تسجيل الخروج',
    'common.showing': 'عرض',
    'common.to': 'إلى',
    'common.of': 'من',
    'common.results': 'نتيجة',
    'common.previous': 'السابق',
    'common.next': 'التالي',
    
    // Dashboard
    'dashboard.title': 'نظرة عامة على لوحة التحكم',
    'dashboard.welcome': 'مرحباً بك في لوحة تحكم إسترحت',
    'dashboard.totalUsers': 'إجمالي المستخدمين',
    'dashboard.totalDoctors': 'إجمالي الأطباء',
    'dashboard.totalPatients': 'إجمالي المرضى',
    'dashboard.transactions': 'المعاملات',
    'dashboard.activeCoupons': 'الكوبونات النشطة',
    'dashboard.totalRevenue': 'إجمالي الإيرادات',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.manageUsers': 'إدارة المستخدمين',
    'dashboard.manageDoctors': 'إدارة الأطباء',
    'dashboard.managePatients': 'إدارة المرضى',
    'dashboard.viewTransactions': 'عرض المعاملات',
    'dashboard.manageCoupons': 'إدارة الكوبونات',
    
    // Login
    'login.title': 'إسترحت للأدمن',
    'login.subtitle': 'قم بتسجيل الدخول للوصول إلى لوحة التحكم',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.signIn': 'تسجيل الدخول',
    'login.signingIn': 'جاري تسجيل الدخول...',
    
    // Doctors
    'doctors.title': 'إدارة الأطباء',
    'doctors.subtitle': 'إدارة الأطباء وملفاتهم الشخصية والتخصصات',
    'doctors.addDoctor': 'إضافة طبيب',
    'doctors.totalDoctors': 'إجمالي الأطباء',
    'doctors.avgRating': 'متوسط التقييم',
    'doctors.totalSessions': 'إجمالي الجلسات',
    'doctors.totalPatients': 'إجمالي المرضى',
    'doctors.search': 'البحث بالاسم أو البريد الإلكتروني أو التخصص...',
    'doctors.doctor': 'الطبيب',
    'doctors.contact': 'جهة الاتصال',
    'doctors.specialization': 'التخصص',
    'doctors.experience': 'الخبرة',
    'doctors.rating': 'التقييم',
    'doctors.price': 'السعر',
    'doctors.patients': 'المرضى',
    'doctors.noDoctors': 'لم يتم العثور على أطباء',
    'doctors.createTitle': 'إضافة طبيب جديد',
    'doctors.fullName': 'الاسم الكامل',
    'doctors.email': 'البريد الإلكتروني',
    'doctors.phone': 'رقم الهاتف',
    'doctors.age': 'العمر',
    'doctors.gender': 'الجنس',
    'doctors.yearsOfExp': 'سنوات الخبرة',
    'doctors.bookingPrice': 'سعر الحجز',
    'doctors.profileImage': 'رابط صورة الملف الشخصي',
    'doctors.bio': 'السيرة الذاتية',
    'doctors.selectGender': 'اختر الجنس',
    'doctors.male': 'ذكر',
    'doctors.female': 'أنثى',
    'doctors.other': 'آخر',
    'doctors.loading': 'جاري تحميل الأطباء...',
    'doctors.empty': 'لا يوجد أطباء',
    'doctors.deleteConfirm': 'هل أنت متأكد أنك تريد حذف هذا الطبيب؟',
    'doctors.viewProfile': 'عرض الملف',
    'doctors.notAvailable': 'غير متوفر',
    'doctors.yearsSuffix': 'سنوات',
    
    // Patients
    'patients.title': 'إدارة المرضى',
    'patients.subtitle': 'إدارة سجلات المرضى والمعلومات',
    'patients.addPatient': 'إضافة مريض',
    'patients.totalPatients': 'إجمالي المرضى',
    'patients.malePatients': 'المرضى الذكور',
    'patients.femalePatients': 'المرضى الإناث',
    'patients.search': 'البحث بالاسم أو البريد الإلكتروني أو الهاتف...',
    'patients.patient': 'المريض',
    'patients.email': 'البريد الإلكتروني',
    'patients.phone': 'الهاتف',
    'patients.age': 'العمر',
    'patients.gender': 'الجنس',
    'patients.registered': 'مسجل',
    'patients.noPatients': 'لم يتم العثور على مرضى',
    'patients.createTitle': 'إضافة مريض جديد',
    'patients.fullName': 'الاسم الكامل',
    'patients.selectGender': 'اختر الجنس',
    'patients.male': 'ذكر',
    'patients.female': 'أنثى',
    'patients.other': 'آخر',
    'patients.profileImage': 'رابط صورة الملف الشخصي',
    'patients.createError': 'فشل إنشاء المريض',
    'patients.createSuccess': 'تم إنشاء المريض بنجاح',
    
    // Bookings
    'bookings.title': 'الحجوزات',
    'bookings.subtitle': 'إدارة جميع المواعيد الطبية',
    'bookings.bookAppointment': 'حجز موعد',
    'bookings.total': 'الإجمالي',
    'bookings.pending': 'قيد الانتظار',
    'bookings.confirmed': 'مؤكد',
    'bookings.completed': 'مكتمل',
    'bookings.cancelled': 'ملغي',
    'bookings.search': 'البحث بالطبيب أو المريض أو الفترة الزمنية...',
    'bookings.allStatus': 'جميع الحالات',
    'bookings.patient': 'المريض',
    'bookings.doctor': 'الطبيب',
    'bookings.date': 'التاريخ',
    'bookings.timeSlot': 'الفترة الزمنية',
    'bookings.status': 'الحالة',
    'bookings.noAppointments': 'لم يتم العثور على مواعيد',
    'bookings.createTitle': 'إنشاء موعد جديد',
    'bookings.selectDoctor': 'اختر طبيباً',
    'bookings.selectPatient': 'اختر مريضاً',
    'bookings.appointmentDate': 'تاريخ الموعد',
    'bookings.createAppointment': 'إنشاء موعد',
    'bookings.loading': 'جاري تحميل المواعيد...',
    'bookings.deleteConfirm': 'هل أنت متأكد أنك تريد حذف هذا الموعد؟',
    'bookings.createError': 'فشل إنشاء الموعد',
    'bookings.unknownPatient': 'مريض غير معروف',
    'bookings.unknownDoctor': 'طبيب غير معروف',
    
    // Reviews
    'reviews.title': 'إدارة التقييمات',
    'reviews.subtitle': 'إدارة تقييمات المرضى والتقييمات',
    'reviews.totalReviews': 'إجمالي التقييمات',
    'reviews.averageRating': 'متوسط التقييم',
    'reviews.search': 'البحث بالتعليق أو التقييم أو معرف الحجز أو معرف المريض أو معرف الطبيب...',
    'reviews.reviewId': 'معرف التقييم',
    'reviews.bookingId': 'معرف الحجز',
    'reviews.patientId': 'معرف المريض',
    'reviews.doctorId': 'معرف الطبيب',
    'reviews.patientEmail': 'البريد الإلكتروني للمريض',
    'reviews.doctorEmail': 'البريد الإلكتروني للطبيب',
    'reviews.rating': 'التقييم',
    'reviews.comment': 'التعليق',
    'reviews.createdAt': 'تاريخ الإنشاء',
    'reviews.noReviews': 'لم يتم العثور على تقييمات',
    'reviews.noComment': 'لا يوجد تعليق',
    'reviews.deleteConfirm': 'هل أنت متأكد أنك تريد حذف هذا التقييم؟',
    
    // Users
    'users.title': 'إدارة المستخدمين',
    'users.subtitle': 'إدارة المستخدمين الإداريين والصلاحيات',
    'users.addUser': 'إضافة مستخدم',
    'users.totalUsers': 'إجمالي المستخدمين',
    'users.activeUsers': 'المستخدمون النشطون',
    'users.inactiveUsers': 'المستخدمون غير النشطين',
    'users.searchPlaceholder': 'ابحث عبر البريد الإلكتروني أو الاسم...',
    'users.table.user': 'المستخدم',
    'users.table.email': 'البريد الإلكتروني',
    'users.table.role': 'الدور',
    'users.table.status': 'الحالة',
    'users.table.lastLogin': 'آخر تسجيل دخول',
    'users.table.actions': 'الإجراءات',
    'users.loading': 'جاري تحميل المستخدمين...',
    'users.empty': 'لا يوجد مستخدمون',
    'users.deleteConfirm': 'هل أنت متأكد أنك تريد حذف هذا المستخدم؟',
    'users.status.active': 'نشط',
    'users.status.inactive': 'غير نشط',
    'users.never': 'لم يسجل الدخول',
    'users.notAvailable': 'غير متوفر',
    'users.createTitle': 'إنشاء مستخدم أدمن جديد',
    'users.createError': 'فشل في إنشاء المستخدم',
    'users.createSuccess': 'تم إنشاء المستخدم بنجاح',
    'users.form.fullName': 'الاسم الكامل',
    'users.form.fullNamePlaceholder': 'اسم الأدمن',
    'users.form.passwordPlaceholder': 'أدخل كلمة مرور قوية',
    'users.form.roleAdmin': 'أدمن',
    'users.form.roleHelp': 'يتم تعيين الدور كـ أدمن بشكل افتراضي.',
    'users.form.creating': 'جاري الإنشاء...',
    'users.form.create': 'إنشاء مستخدم',
    
    // Transactions
    'transactions.title': 'المعاملات',
    'transactions.subtitle': 'مراقبة جميع المعاملات المالية والمدفوعات',
    'transactions.totalAmount': 'إجمالي المبلغ',
    'transactions.successful': 'الناجحة',
    'transactions.pending': 'قيد الانتظار',
    'transactions.failed': 'الفاشلة',
    'transactions.searchPlaceholder': 'البحث بمعرّف الطبيب أو المريض أو الحجز...',
    'transactions.filter.all': 'جميع الحالات',
    'transactions.filter.success': 'الناجحة',
    'transactions.filter.waiting': 'قيد الانتظار',
    'transactions.filter.failed': 'الفاشلة',
    'transactions.filter.currency': 'تصفية حسب العملة',
    'transactions.filter.currencyAll': 'جميع العملات',
    'transactions.filter.currencyUSD': 'دولار أمريكي',
    'transactions.filter.currencyMRU': 'أوقية موريتانية',
    'transactions.table.id': 'معرّف المعاملة',
    'transactions.table.type': 'النوع',
    'transactions.table.doctorId': 'معرّف الطبيب',
    'transactions.table.patientId': 'معرّف المريض',
    'transactions.table.amount': 'المبلغ',
    'transactions.table.status': 'الحالة',
    'transactions.table.date': 'التاريخ',
    'transactions.table.paymentGateway': 'بوابة الدفع',
    'transactions.table.paymentCurrency': 'العملة',
    'transactions.table.operationId': 'معرّف العملية',
    'transactions.empty': 'لم يتم العثور على معاملات',
    'transactions.viewDetails': 'عرض التفاصيل',
    'transactions.detailTitle': 'تفاصيل المعاملة',
    'transactions.detail.doctor': 'الطبيب',
    'transactions.detail.patient': 'المريض',
    'transactions.detail.transactionInfo': 'معلومات المعاملة',
    'transactions.detail.name': 'الاسم',
    'transactions.detail.email': 'البريد الإلكتروني',
    'transactions.detail.id': 'المعرف',
    
    // Payment Plans
    'paymentPlans.title': 'خطط الدفع',
    'paymentPlans.subtitle': 'إدارة خطط الدفع للأطباء',
    'paymentPlans.addPlan': 'إضافة خطة',
    'paymentPlans.total': 'إجمالي الخطط',
    'paymentPlans.active': 'النشطة',
    'paymentPlans.search': 'البحث باسم الخطة أو الطبيب...',
    'paymentPlans.table.name': 'اسم الخطة',
    'paymentPlans.table.doctor': 'الطبيب',
    'paymentPlans.table.price': 'السعر',
    'paymentPlans.table.duration': 'المدة',
    'paymentPlans.table.status': 'الحالة',
    'paymentPlans.empty': 'لا توجد خطط دفع',
    'paymentPlans.deleteConfirm': 'هل أنت متأكد من حذف هذه الخطة؟',
    
    // Patient Plan Subscriptions
    'subscriptions.title': 'اشتراكات الخطط',
    'subscriptions.subtitle': 'عرض وإدارة اشتراكات المرضى بالخطط',
    'subscriptions.total': 'الإجمالي',
    'subscriptions.active': 'النشطة',
    'subscriptions.expired': 'المنتهية',
    'subscriptions.search': 'البحث بالمريض أو الخطة...',
    'subscriptions.table.patient': 'المريض',
    'subscriptions.table.plan': 'الخطة',
    'subscriptions.table.status': 'الحالة',
    'subscriptions.table.startDate': 'البداية',
    'subscriptions.table.endDate': 'النهاية',
    'subscriptions.empty': 'لا توجد اشتراكات',
    'subscriptions.deleteConfirm': 'هل أنت متأكد من حذف هذا الاشتراك؟',
    
    // Coupons
    'coupons.title': 'إدارة الكوبونات',
    'coupons.subtitle': 'إنشاء وإدارة كوبونات الخصم',
    'coupons.addCoupon': 'إضافة كوبون',
    'coupons.total': 'إجمالي الكوبونات',
    'coupons.active': 'النشطة',
    'coupons.used': 'المستخدمة',
    'coupons.expired': 'المنتهية',
    'coupons.search': 'البحث برمز الكوبون أو المستخدم...',
    'coupons.table.code': 'رمز الكوبون',
    'coupons.table.value': 'القيمة',
    'coupons.table.forUser': 'لصالح المستخدم',
    'coupons.table.validUntil': 'صالحة حتى',
    'coupons.table.usage': 'عدد الاستخدامات',
    'coupons.table.status': 'الحالة',
    'coupons.empty': 'لم يتم العثور على كوبونات',
    'coupons.allUsers': 'جميع المستخدمين',
    'coupons.usage.oneTime': 'مرة واحدة',
    'coupons.usage.uses': 'استخدامات',
    'coupons.status.active': 'نشط',
    'coupons.status.used': 'مستخدم',
    'coupons.status.expired': 'منتهي',
    'coupons.deleteConfirm': 'هل أنت متأكد أنك تريد حذف هذا الكوبون؟',
    'coupons.createTitle': 'إنشاء كوبون جديد',
    'coupons.form.code': 'رمز الكوبون',
    'coupons.form.value': 'قيمة الخصم',
    'coupons.form.valuePlaceholder': '10% أو 10$',
    'coupons.form.validUntil': 'صالحة حتى',
    'coupons.form.forUser': 'لصالح مستخدم (اختياري)',
    'coupons.form.forUserPlaceholder': 'معرف المستخدم أو البريد الإلكتروني',
    'coupons.form.forUserHelp': 'اتركه فارغاً ليكون لجميع المستخدمين',
    'coupons.form.oneTimeUse': 'استخدام مرة واحدة فقط',
    'coupons.form.numberOfUses': 'عدد الاستخدامات',
    'coupons.form.creating': 'جاري الإنشاء...',
    'coupons.form.create': 'إنشاء كوبون',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [mounted, setMounted] = useState(false);
  // Start with 'en' on both server and client to avoid hydration mismatch
  const [language, setLanguageState] = useState<Language>('en');

  // Initialize language after mount to avoid hydration mismatch
  useEffect(() => {
    setMounted(true);
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      const lang = (saved === 'en' || saved === 'ar') ? saved : 'en';
      // The inline script already set the direction, but update state to match
      setLanguageState(lang);
      // Ensure direction matches (script should have set it, but double-check)
      if (document.documentElement.dir !== (lang === 'ar' ? 'rtl' : 'ltr')) {
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
      }
      document.documentElement.lang = lang;
    }
  }, []);

  useEffect(() => {
    if (mounted && typeof window !== 'undefined') {
      localStorage.setItem('language', language);
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = language;
    }
  }, [language, mounted]);

  // Use language state directly after mount to ensure reactivity
  // Before mount, always false to match server render
  const isRTL = mounted ? language === 'ar' : false;

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // Immediately update document direction for instant visual feedback
    if (typeof window !== 'undefined') {
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = lang;
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

